


data "amazon-ami" "autogenerated_1" {
  filters = {
    virtualization-type = "hvm"
  }
  most_recent = true
  owners =  ["363638483937"]
  region      = "us-east-1"
}

source "amazon-ebs" "aws" {
  ami_name      = "packer6"
  instance_type = "t2.micro"
  region        = "us-east-1"
  run_tags = {
    Name = "packer6"
  }
  source_ami   = "ami-0aa7d40eeae50c9a9"
  ssh_username = "ec2-user"
  subnet_id    = "subnet-0b8f9a7b97fd1edf0"
  iam_instance_profile =  "ssm"
  ssh_interface        = "session_manager"
  communicator         = "ssh"
  tags = {
    Base_AMI_Name = "packer6"
  }
}

build {
  sources = ["source.amazon-ebs.aws"]

  provisioner "shell" {
    scripts = ["Inspector_Agent_Install.sh","jdk1.8.sh","vul_scan.py"]
  }

}
