
variable "project_id" {
  type    = string
  default = "${env("GCP_PROJECT_ID")}"
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture                       = "x86_64"
    "block-device-mapping.volume-type" = "gp2"
    name                               = "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"
    root-device-type                   = "ebs"
    virtualization-type                = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "ap-south-1"
}


source "amazon-ebs" "aws" {
  ami_name      = "packer-Build-{{ clean_resource_name `${timestamp()}` }}"
  instance_type = "t2.micro"
  region        = "ap-south-1"
  run_tags = {
    Name = "packer-Build-{{ clean_resource_name `${timestamp()}` }}"
  }
  source_ami   = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username = "ubuntu"
  subnet_id    = "subnet-03945c46a0d9205c3"
  tags = {
    Base_AMI_Name = "{{ .SourceAMIName }}"
    OS_Version    = "ubuntu"
  }
}

build {
  sources = ["source.amazon-ebs.aws"]
}

source "googlecompute" "gcp" {
  communicator       = "ssh"
  enable_secure_boot = true
  enable_vtpm        = true
  image_licenses     = ["projects/vm-options/global/licenses/enable-vmx"]
  project_id             = "prj-zee-poc-atm-new-5c6b"
  source_image_family    = "centos-stream-8"
  ssh_handshake_attempts = 20
  ssh_username           = "packer"
  subnetwork             = "nodes-cidr"
  tags                   = ["iapssh", "https-server", "http-server", "testssh"]
  wait_to_add_ssh_keys   = "20s"
  service_account_email = "github-actions-service-account@prj-zee-poc-atm-new-5c6b.iam.gserviceaccount.com"
  zone                   = "asia-south1-a"
    metadata = {
    enable-oslogin = "FALSE"
  }
}

build {
  sources = ["source.googlecompute.gcp"]
}
